services:
  - type: web
    name: portfolio-2
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NITRO_PRESET
        value: render_com
